### ISSUE TITLE
setup.pyが実行できない

### ISSUE THREAD

**Issue by Miya-imslab** [BerkeleyAutomation/autolab_core#43]
こんにちは
このリポジトリをgit cloneしてsetup.pyを実行しようとしたところ以下のエラーが出ました。
解決策がれば教えていただきたいです。

member@thinkpad-p15:~/3catkin_ws/src/autolab_core$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to autolab_core.egg-info/requires.txt
writing autolab_core.egg-info/PKG-INFO
writing top-level names to autolab_core.egg-info/top_level.txt
writing dependency_links to autolab_core.egg-info/dependency_links.txt
reading manifest file 'autolab_core.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'autolab_core.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/points.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/version.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/json_serialization.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/camera_intrinsics.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/dual_quaternion.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/rigid_transformations.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/chessboard_registration.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/point_registration.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/data_stream_syncer.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/csv_model.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/experiment_logger.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/feature_matcher.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/completer.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/primitives.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/logger.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/image.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/tensor_dataset.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/__init__.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/transformations.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/learning_analysis.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/data_stream_recorder.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/random_variables.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/constants.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/features.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/dist_metrics.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/utils.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/detector.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/yaml_config.py -> build/bdist.linux-x86_64/egg/autolab_core
copying build/lib.linux-x86_64-2.7/autolab_core/orthographic_intrinsics.py -> build/bdist.linux-x86_64/egg/autolab_core
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/points.py to points.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/version.py to version.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/json_serialization.py to json_serialization.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/camera_intrinsics.py to camera_intrinsics.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/dual_quaternion.py to dual_quaternion.pyc
  File "build/bdist.linux-x86_64/egg/autolab_core/dual_quaternion.py", line 94
    f"Got {qd_wxyz[0]}"
    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/autolab_core/rigid_transformations.py to rigid_transformations.pyc
  File "build/bdist.linux-x86_64/egg/autolab_core/rigid_transformations.py", line 417
    f"Cannot transform points in frame {points.frame} with "
                                                           ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/autolab_core/chessboard_registration.py to chessboard_registration.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/point_registration.py to point_registration.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/data_stream_syncer.py to data_stream_syncer.pyc
  File "build/bdist.linux-x86_64/egg/autolab_core/data_stream_syncer.py", line 87
    f"Potential timeout! {timeout_names} not yet returned "
                                                          ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/autolab_core/csv_model.py to csv_model.pyc
  File "build/bdist.linux-x86_64/egg/autolab_core/csv_model.py", line 42
    f"For header {key}, type {val}"
    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/autolab_core/experiment_logger.py to experiment_logger.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/feature_matcher.py to feature_matcher.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/completer.py to completer.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/primitives.py to primitives.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/logger.py to logger.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/image.py to image.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/tensor_dataset.py to tensor_dataset.pyc
  File "build/bdist.linux-x86_64/egg/autolab_core/tensor_dataset.py", line 495
    f"Datapoint index {datapoint_index} is greater than the "
                                                            ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/autolab_core/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/transformations.py to transformations.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/learning_analysis.py to learning_analysis.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/data_stream_recorder.py to data_stream_recorder.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/random_variables.py to random_variables.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/constants.py to constants.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/features.py to features.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/dist_metrics.py to dist_metrics.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/detector.py to detector.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/yaml_config.py to yaml_config.pyc
byte-compiling build/bdist.linux-x86_64/egg/autolab_core/orthographic_intrinsics.py to orthographic_intrinsics.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying autolab_core.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying autolab_core.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying autolab_core.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying autolab_core.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying autolab_core.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/autolab_core-1.1.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing autolab_core-1.1.1-py2.7.egg
Removing /usr/local/lib/python2.7/dist-packages/autolab_core-1.1.1-py2.7.egg
Copying autolab_core-1.1.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
autolab-core 1.1.1 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/autolab_core-1.1.1-py2.7.egg
Processing dependencies for autolab-core==1.1.1
Searching for joblib
Reading https://pypi.org/simple/joblib/
Downloading https://files.pythonhosted.org/packages/45/dd/a5435a6902d6315241c48a5343e6e6675b007e05d3738ed97a7a47864e53/joblib-1.2.0.tar.gz#sha256=e1cee4a79e4af22881164f218d4311f60074197fb707e082e803b61f6d137018
Best match: joblib 1.2.0
Processing joblib-1.2.0.tar.gz
Writing /tmp/easy_install-yUke5i/joblib-1.2.0/setup.cfg
Running joblib-1.2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-yUke5i/joblib-1.2.0/egg-dist-tmp-NorNer
Traceback (most recent call last):
  File "setup.py", line 62, in <module>
    "ros": ["rospkg", "catkin_pkg", "empy"],
  File "/home/member/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/member/.local/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/member/.local/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/home/member/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 424, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/member/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 666, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/member/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 713, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/member/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 758, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/member/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/home/member/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/home/member/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/home/member/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/member/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 711, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/member/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 896, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/member/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1164, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/member/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1150, in run_setup
    run_setup(setup_script, args)
  File "/home/member/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/member/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/member/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/member/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/member/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/member/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/member/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/member/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-yUke5i/joblib-1.2.0/setup.py", line 5, in <module>
    import os
  File "/tmp/easy_install-yUke5i/joblib-1.2.0/joblib/__init__.py", line 113, in <module>
  File "/tmp/easy_install-yUke5i/joblib-1.2.0/joblib/memory.py", line 271
    raise new_exc from exc
                     ^
SyntaxError: invalid syntax

**Comment by AhChaoispracting** [comment]
Excuse me, I have encountered the same problem as you, did you solve this problem?
